### ISSUE TITLE
`MVC-Action-with-View`: Create `Book`

### ISSUE THREAD

**Issue by SardorSohinazarov** [NET-Bootcamp-N11/BookStore#51]

**Comment by QosimovIbrohim** [comment]
oldim

**Comment by Tohirjon-Odilov** [comment]
Olishiz muhimmas

**Comment by QosimovIbrohim** [comment]
![image](https://github.com/NET-Bootcamp-N11/BookStore/assets/128721965/61fc9797-82f5-457e-b6ba-b02efe808735)
toyyor og'a
