### ISSUE TITLE
Queries : Create `GetBookByIdQuery` with `GetBookByIdQueryHandler`

### ISSUE THREAD

**Issue by SardorSohinazarov** [NET-Bootcamp-N11/BookStore#9]

**Comment by OtabekgithubJava** [comment]
.

**Comment by OtabekgithubJava** [comment]
using BookStore.Application.Abstractions;
using BookStore.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Application.useCases.Books.Queries
{
    public class GetBookByIdQuery
    {
        public long Id { get; set; }

        private readonly IAppDbContext _appDb;

        public GetBookByIdQuery(IAppDbContext appDb)
        {
            _appDb = appDb;
        }
        
        public async Task<Book> Handle(GetBookByIdQuery request, CancellationToken cancellationToken)
        {
            var user = await _appDb.Books.FirstOrDefaultAsync(x=> x.Id == request.Id);
            return user;
        }
    }
}



closed #9

**Comment by akmalxoja** [comment]
zo'r
